
server:
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: CommandService
  zipkin:
    base-url: http://localhost:9411/

